//
// Generated file, do not edit! Created by opp_msgc 4.3 from Data2BSMessage.msg.
//

#ifndef _DATA2BSMESSAGE_M_H_
#define _DATA2BSMESSAGE_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0403
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// cplusplus {{
#include "ClusterMessage_m.h"
// }}



/**
 * Class generated from <tt>Data2BSMessage.msg</tt> by opp_msgc.
 * <pre>
 * packet Data2BSMessage extends ClusterMessage
 * {
 *     
 *         int data;
 * };
 * </pre>
 */
class Data2BSMessage : public ::ClusterMessage
{
  protected:
    int data_var;

  private:
    void copy(const Data2BSMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Data2BSMessage&);

  public:
    Data2BSMessage(const char *name=NULL, int kind=0);
    Data2BSMessage(const Data2BSMessage& other);
    virtual ~Data2BSMessage();
    Data2BSMessage& operator=(const Data2BSMessage& other);
    virtual Data2BSMessage *dup() const {return new Data2BSMessage(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getData() const;
    virtual void setData(int data);
};

inline void doPacking(cCommBuffer *b, Data2BSMessage& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, Data2BSMessage& obj) {obj.parsimUnpack(b);}


#endif // _DATA2BSMESSAGE_M_H_
